from math import floor


class Language:
    def __init__(self):
        self.translations = {
            'english': {
                "1: NEW SAVE": "1: NEW SAVE",
                "1: NEW RUN": "1: NEW RUN",
                "2: EQUIPMENT": "2: EQUIPMENT",
                "3: MENU": "3: MENU",
                "4: EXIT": "4: EXIT",
                "1: CONTINUE": "1: CONTINUE",
                "2: NEW RUN": "2: NEW RUN",
                "3: SETTINGS": "3: SETTINGS",
                "1: SWITCH LANGUAGES TO 简体中文": "1: SWITCH LANGUAGES TO 简体中文",
                "2: DELETE SAVE ☠": "2: DELETE SAVE ☠",
                "Boss can only be defeated once in each round of the game!": "Boss can only be defeated once in each round of the game!",
                "Do you want to continue ☠? (y/n): ": "Do you want to continue ☠? (y/n): ",
                "Choose: ": "Choose: ",
                "Invalid Choice!": "Invalid Choice!",
                "Fail to save:": "Fail to save:",
                "Saved file is broken!": "Save file is broken!",
                "File to load:": "File to load:",
                "Unknown error:": "Unknown error:",
                "Fail to apply data:": "Fail to apply data:",
                "Save file deleted": "Save file deleted:",
                "Please enter ID to fight": "Please enter ID to fight:",
                "for the first enemy)t": "for the first enemy)",
                " for torso equipment)!": " for torso equipment)!",
                "Score: Highest LEVEL: ": "Score: Highest LEVEL: ",
                "Lose": "Lose",
                "Consume": "Consume",
                "Gain": "Gain",
                "Your energy: ": "Your energy: ",
                "FOE ID(001/002): FIGHT": "FOE ID(001/002): FIGHT",
                "2: OPTION": "2: OPTION",
                "Input foot equipment ID you gonna swap, or purchase(001/002...):": "Input foot equipment ID you gonna swap, or purchase(001/002...):",
                "Input shield ID you gonna swap, or purchase(001/002...):": "Input shield ID you gonna swap, or purchase(001/002...):",
                "Input hand proof ID you gonna swap, or purchase(001/002...):": "Input hand proof ID you gonna swap, or purchase(001/002...):",
                "Input leg guard ID you gonna swap, or purchase(001/002...):": "Input leg guard ID you gonna swap, or purchase(001/002...):",
                "Input torso equipment ID you gonna swap, or purchase(001/002...):": "Input torso equipment ID you gonna swap, or purchase(001/002...):",
                "Input weapon ID you gonna swap, or purchase(001/002...):": "Input weapon ID you gonna swap, or purchase(001/002...):",
                "1: WEAPON": "1: WEAPON",
                "2: TORSO": "2: TORSO",
                "3: LEG": "3: LEG",
                "4: HAND": "4: HAND",
                "5: SHIELD": "5: SHIELD",
                "6: FOOT": "6: FOOT",
                "7: RETURN": "7: RETURN",
                "1: STATS": "1: STATS",
                "3: RETURN": "3: RETURN",
                "4: MENU": "4: MENU",
                "You don't have that unknown equipment!": "You don't have that unknown equipment!",
                "Switched to ": "Switched to ",
                " successfully!": "successfully!",
                "Your GOLD:": "Your GOLD:",
                "You don't have enough GOLD!": "You don't have enough GOLD!",
                "Do you want to buy": "Do you want to buy",
                "and equip it immediately? Cost:": "and equip it immediately? Cost:",
                "Gold:": "Gold:",
                "Current:": "Current:",
                "Element:": "Element:",
                "Resistance:": "Resistance:",
                "You got": "You got",
                "from": "from",
                "piercingRESIS:": "piercingRESIS:",
                "slashingRESIS:": "slashingRESIS:",
                "bludgeoningRESIS:": "bludgeoningRESIS:",
                "fireRESIS:": "fireRESIS:",
                "iceRESIS:": "iceRESIS:",
                "thunderRESIS:": "thunderRESIS:",
                "holyRESIS:": "holyRESIS:",
                "darkRESIS:": "darkRESIS:",
                "weapon element:": "weapon element:",
                "Victory is assured!": "Victory is assured!",
                "You are likely to win this": "You are likely to win this",
                "This seems like a fair fight": "This seems like a fair fight",
                "You face a challenge": "You face a challenge",
                "Your opponent is too powerful": "Your opponent is too powerful",
                "The battle looks impossible": "The battle looks impossible",
                "The battle will take too much time": "The battle will take too much time",
                "now drops 200% EXP!": "now drops 200% EXP!",
                "is fragile!": "is fragile!",
                "is exhausted!": "is exhausted!",
                "now drops 200% MONEY!": "now drops 200% MONEY!",
                "is exposing its weakness!": "is exposing its weakness!",
                "is at last gasp!!!": "is at last gasp!!!",
                "is slow in movement!": "is slow in movement!",
                "Looted": "Looted",
                "Allocation cancelled!": "Allocation cancelled!",
                "Please enter valid FORMAT": "Please enter valid FORMAT",
                "means 66.6% points for HP and 33.3% for AP, etc)!": "means 66.6% points for HP and 33.3% for AP, etc)!",
                "Allocation of": "Allocation of",
                "is successful!": "is successful!",
                "No SP available!": "No SP available!",
                "Allocation after battle enabled!": "Allocation after battle enabled!",
                "Allocation after battle disabled!": "Allocation after battle disabled!",
                "2: Toggle allocation after battle, current:": "2: Toggle allocation after battle, current:",
                "(1 1 0 0 0,etc): Allocation strategy": "(1 1 0 0 0,etc): Allocation strategy",
                "UP": "UP",
                "Gained!": "Gained!",
                "You lose...": "You lose...",
                "Nice dodge!": "Nice dodge!",
                "hits you": "hits you",
                "BRUTALLY": "BRUTALLY",
                "for": "for",
                "You": "You",
                "absorb": "absorb",
                "recovered": "recovered",
                "hits you for": "hits you for",
                "attenuated": "attenuated",
                "You gained": "You gained",
                "You have defeated": "You have defeated",
                "You miss!": "You miss!",
                "You hit": "You hit",
                "powerfully": "powerfully",
                "but it": "but it",
                "absorbed": "absorbed",
                "You critically hit": "You critically hit",
                "devastatingly": "devastatingly",
                "hit": "hit",
                "Progress cancelled!": "Progress cancelled!",
                "Please enter F to fight, or R to retreat!": "Please enter F to fight, or R to retreat!",
                "F:Fight!": "F:Fight!",
                "R:Retreat!": "R:Retreat!",
                "Damage Rate:": "Damage Rate:",
                "Damage Reduction:": "Damage Reduction:",
                "Hit Rate:": "Hit Rate:",
                "Dodge Rate:": "Dodge Rate:",
                "You encountered": "You encountered",


                "green slime": "green slime",
                "dwarf": "dwarf",
                "dirt doll": "dirt doll",
                "green bush": "green bush",
                "forest sprite": "forest sprite",
                "cat warrior": "cat warrior",
                "cat mage": "cat mage",
                "cat rogue": "cat rogue",
                "doppelganger": "doppelganger",
                "baby shapeshifter": "baby shapeshifter",
                "haunting tree": "haunting tree",
                "deep gnome": "deep gnome",
                "crow": "crow",
                "huge green slime":"huge green slime",
                "flying eye": "flying eye",
                "giant lizard": "giant lizard",
                "black bear": "black bear",
                "haunting soul": "haunting soul",

                "fist": "fist",
                "dagger": "dagger",
                "knife": "knife",
                "oak wand": "oak wand",
                "copper gladius": "copper gladius",
                "hand axe": "hand axe",
                "toothy club":"toothy club",
                "rusty crowbar": "rusty crowbar",
                "light hammer": "light hammer",
                "handsaw": "handsaw",
                "claw hammer": "claw hammer",
                "iron sword": "iron sword",
                "long spear": "long spear",
                "rogue dagger": "rogue dagger",

                "bare": "bare",
                "worn vest": "worn vest",
                "woolen shirt": "woolen shirt",
                "leather jacket": "leather jacket",
                "chain armor": "chain armor",
                "scale armor": "scale armor",
                "light plate": "light plate",

                "pants": "pants",
                "scotland skirt": "scotland skirt",
                "casual trousers": "casual trousers",
                "leather pants": "leather pants",
                "shin guard": "shin guard",
                "soft lapboard": "soft lapboard",
                "fiber legging": "fiber legging",

                "couch-grass lid": "couch-grass lid",
                "shattered wooden shield": "shattered wooden shield",
                "softwood round shield": "softwood round shield",
                "copper shield": "copper shield",
                "iron shield": "iron shield",
                "steel shield": "steel shield",

                "woolen gloves": "woolen gloves",
                "fabricated mittens": "fabricated mittens",
                "leather gloves": "leather gloves",
                "oven gloves": "oven gloves",
                "padded gloves": "padded gloves",
                "gauntlets": "gauntlets",

                "clog": "clog",
                "cloth shoes": "cloth shoes",
                "rattan sandal": "rattan sandal",
                "worn sneaker": "worn sneaker",
                "casual shoes": "casual shoes",
                "traveller boots": "traveller boots",
                "plate boots": "plate boots"


            },

            '简体中文':{
                "1: NEW SAVE": "1: 新存档",
                "1: NEW RUN": "1: 新游戏",
                "2: EQUIPMENT": "2: 装备",
                "3: MENU": "3: 菜单",
                "4: EXIT": "4: 退出",
                "1: CONTINUE": "1: 继续游戏",
                "2: NEW RUN": "2: 新游戏",
                "3: SETTINGS": "3: 设置",
                "1: SWITCH LANGUAGES TO 简体中文": "1: 将语言切换为 English",
                "2: DELETE SAVE ☠": "2: 删除存档 ☠",
                "Boss can only be defeated once in each round of the game!": "Boss每轮游戏只能击败一次!",
                "Do you want to continue ☠? (y/n): ": "你真的要删除角色存档吗 ☠? (y/n): ",
                "Choose: ": "选择: ",
                "Invalid Choice!": "无效选项!",
                "Fail to save:": "存档失败:",
                "Saved file is broken!": "存档已损坏!",
                "File to load:": "加载失败:",
                "Unknown error:": "未知错误:",
                "Fail to apply data:": "读取数据失败:",
                "Save file deleted": "存档已删除:",
                "Please enter ID to fight": "请输入想要挑战的怪物ID:",
                "for the first enemy)": "代表第一个敌人)",
                " for torso equipment)!": " 代表躯干部位的装备)!",
                "Score: Highest LEVEL: ": "分数: 最高等级: ",
                "You run out of energy!": "你没能量了!",
                "Lose": "失去",
                "Consume": "消耗",
                "Gain": "获得",
                "Your energy: ": "你的能量: ",
                "FOE ID(001/002): FIGHT": "怪物 ID(001/002): 挑战",
                "2: OPTION": "2: 选项",
                "Input foot equipment ID you gonna swap, or purchase(001/002...):": "请输入你想穿戴或购买的脚部装备的ID(001/002...):",
                "Input shield ID you gonna swap, or purchase(001/002...):": "请输入你想穿戴或购买的盾牌的ID(001/002...):",
                "Input hand proof ID you gonna swap, or purchase(001/002...):": "请输入你想穿戴或购买的护手ID(001/002...):",
                "Input leg guard ID you gonna swap, or purchase(001/002...):": "请输入你想穿戴或购买的护腿ID(001/002...):",
                "Input torso equipment ID you gonna swap, or purchase(001/002...):": "请输入你想穿戴或购买的躯干部位装备的ID(001/002...):",
                "Input weapon ID you gonna swap, or purchase(001/002...):": "请输入你想穿戴或购买的武器ID(001/002...):",
                "1: WEAPON": "1: 武器   ",
                "2: TORSO": "2: 躯干  ",
                "3: LEG": "3: 腿部",
                "4: HAND": "4: 手部 ",
                "5: SHIELD": "5: 盾牌   ",
                "6: FOOT": "6: 脚部 ",
                "7: RETURN": "7: 返回",
                "1: STATS": "1: 属性",
                "3: RETURN": "3: 返回",
                "4: MENU": "4: 主菜单",
                "You don't have that unknown equipment!": "你不知道那件装备是什么!",
                "Switched to ": "成功切换到 ",
                " successfully!": "!",
                "Your GOLD:": "你的金币:",
                "You don't have enough GOLD!": "你的钱不够!",
                "Do you want to buy": "你想买",
                "and equip it immediately? Cost:": "并立即装备它吗? 花费:",
                "Gold:": "金币:",
                "Current:": "当前:",
                "Element:": "元素:",
                "Resistance:": "元素抵抗:",
                "You got": "你获得了",
                "from": "，完胜",
                "piercingRESIS:": "穿刺抗性:",
                "slashingRESIS:": "挥砍抗性:",
                "bludgeoningRESIS:": "钝击抗性:",
                "fireRESIS:": "火焰抗性:",
                "iceRESIS:": "寒冰抗性:",
                "thunderRESIS:": "闪电抗性:",
                "holyRESIS:": "神圣抗性:",
                "darkRESIS:": "黑暗抗性:",
                "weapon element:": "武器元素:",
                "Victory is assured!": "胜利是有保证的!",
                "You are likely to win this": "你很有可能赢下这场战斗",
                "This seems like a fair fight": "这似乎是一场公平对决",
                "You face a challenge": "你将面临挑战",
                "Your opponent is too powerful": "你的对手太强大了",
                "The battle looks impossible": "这场战斗看起来不可能取胜",
                "The battle will take too much time": "这场战斗将花费大量时间",
                "now drops 200% EXP!": "现在掉落 200% EXP!",
                "is fragile!": "不堪一击!",
                "is exhausted!": "精疲力竭!",
                "now drops 200% MONEY!": "现在掉落 200% 金币!",
                "is exposing its weakness!": "暴露出了弱点!",
                "is at last gasp!!!": "奄奄一息!!!",
                "is slow in movement!": "行动迟缓!",
                "Looted": "掠夺了",
                "Allocation cancelled!": "分配取消!",
                "Please enter valid FORMAT": "请输入有效的格式",
                "means 66.6% points for HP and 33.3% for AP, etc)!": "代表 66.6% 的点数给 HP, 33.3% 给 AP, 以此类推)!",
                "Allocation of": "",
                "is successful!": "属性点分配成功!",
                "No SP available!": "没有属性点可用!",
                "Allocation after battle enabled!": "战斗后自动进入分配界面已启用!",
                "Allocation after battle disabled!": "战斗后自动进入分配界面已禁用!",
                "2: Toggle allocation after battle, current:": "2: 战斗后打开分配界面, 当前:",
                "(1 1 0 0 0,etc): Allocation strategy": "(1 1 0 0 0,以此类推): 分配策略",
                "UP": "升级",
                "Gained!": "本次获得!",
                "You lose...": "你输了...",
                "Nice dodge!": "躲得好!",
                "hits you": "命中了你",
                "BRUTALLY": "[迎头痛击]",
                "for": "造成",
                "You": "你",
                "absorb": "[吸收了]",
                "recovered": "[恢复了]",
                "hits you for": "命中了你，造成",
                "attenuated": "[微弱的]",
                "You gained": "你获得了",
                "You have defeated": "你击败了",
                "You miss!": "你失手了!",
                "You hit": "你命中了",
                "powerfully": "[强力一击]",
                "but it": "但它",
                "absorbed": "[吸收了]",
                "You critically hit": "你会心一击命中",
                "devastatingly": "[毁灭般]",
                "hit": "命中了",
                "Progress cancelled!": "进程取消!",
                "Please enter F to fight, or R to retreat!": "请按 F 战斗, 或 R 撤退!",
                "F:Fight!": "F:战斗!",
                "R:Retreat!": "R:撤退!",
                "Damage Rate:": "伤害率:",
                "Damage Reduction:": "减伤率:",
                "Hit Rate:": "命中率:",
                "Dodge Rate:": "闪避率:",
                "You encountered": "你遭遇了",

                "green slime": "绿史莱姆",
                "dwarf": "矮人",
                "dirt doll": "土制玩偶",
                "green bush": "绿灌木",
                "forest sprite": "森林之灵",
                "cat warrior": "猫战士",
                "cat mage": "魔法师猫",
                "cat rogue": "盗贼猫",
                "doppelganger": "人形暗影",
                "baby shapeshifter": "变形兽幼崽",
                "haunting tree": "闹鬼树",
                "deep gnome": "地底侏儒",
                "crow": "乌鸦",
                "huge green slime": "巨型绿史莱姆",
                "flying eye": "飞行之眼",
                "giant lizard": "巨蜥",
                "black bear": "黑熊",
                "haunting soul": "游荡的灵魂",

                "fist": "拳头",
                "dagger": "匕首",
                "knife": "小刀",
                "oak wand": "橡木魔杖",
                "copper gladius": "铜短剑",
                "hand axe": "手斧",
                "toothy club": "狼牙棒",
                "rusty crowbar": "生锈的撬棍",
                "light hammer": "轻锤",
                "handsaw": "手锯",
                "claw hammer": "钉锤",
                "iron sword": "铁剑",
                "long spear": "长枪",
                "rogue dagger": "盗贼长匕首",

                "bare": "无",
                "worn vest": "旧背心",
                "woolen shirt": "羊毛衫",
                "leather jacket": "皮夹克",
                "chain armor": "链甲",
                "scale armor": "鳞甲",
                "light plate": "轻型板甲",

                "pants": "短裤",
                "scotland skirt": "苏格兰短裙",
                "casual trousers": "休闲裤",
                "leather pants": "皮裤",
                "shin guard": "护胫",
                "soft lapboard": "软膝板",
                "fiber legging": "高纤打底裤",

                "couch-grass lid": "茅草盖",
                "shattered wooden shield": "破损的木盾",
                "softwood round shield": "软木小圆盾",
                "copper shield": "铜盾",
                "iron shield": "铁盾",
                "steel shield": "钢盾",

                "woolen gloves": "羊绒手套",
                "fabricated mittens": "针织手套",
                "leather gloves": "皮手套",
                "oven gloves": "隔热手套",
                "padded gloves": "加厚手套",
                "gauntlets": "金属护手",

                "clog": "木屐",
                "cloth shoes": "布鞋",
                "rattan sandal": "藤条凉鞋",
                "worn sneaker": "旧运动鞋",
                "casual shoes": "休闲鞋",
                "traveller boots": "旅行靴",
                "plate boots": "板靴"
            }
        }
        self.lang = 'english'

    def set_lang(self, lang):
        if lang in self.translations:
            self.lang = lang
            return True
        return False

    def t(self, key):
        return self.translations.get(self.lang, {}).get(key, f'[{key}]')


def get_display_width(text):
    width = 0
    for char in text:
        if '\u4e00' <= char <= '\u9fff':
            width += 2
        else:
            width += 1
    width = floor(width)
    return width


def pad_chinese_text(text, target_width, fillchar=' '):
    current_width = get_display_width(text)
    if current_width >= target_width:
        return text
    return text + fillchar * (target_width - current_width)
